CREATE OR REPLACE PACKAGE PckageUser AS 
	PROCEDURE PRC_INSERT_USER(P_Nome_In IN VARCHAR2, P_CPF_In IN NUMBER, P_DataNascimento_In IN TIMESTAMP, P_UsuarioId_Out OUT NUMBER);
	PROCEDURE PRC_SELECT_USER;	
	PROCEDURE PRC_UPDATE_USER(P_UsuarioId_In IN NUMBER,	P_Nome_In IN VARCHAR2, P_CPF_In IN NUMBER, P_DataNascimento_In IN DATE, P_StatusId_In IN NUMBER);
	PROCEDURE PRC_DELETE_USER(P_UsuarioId_In IN NUMBER);
END; 