CREATE TABLE StatusUsuario
(
	StatusId NUMBER GENERATED BY DEFAULT AS IDENTITY,
	Nome VARCHAR2(30) NOT NULL,
	DataCriacao TIMESTAMP NOT NULL,
	PRIMARY KEY(StatusId)
);

INSERT INTO StatusUsuario(Nome, DataCriacao) VALUES('Ativo', SYSDATE);
INSERT INTO StatusUsuario(Nome, DataCriacao) VALUES('Inativo', SYSDATE);